# Generated by Django 4.0.4 on 2022-06-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculaPrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_stamp', models.DateTimeField(auto_now_add=True)),
                ('data_evento', models.DateField()),
                ('evento', models.CharField(max_length=254)),
                ('prazo', models.IntegerField(default=15)),
                ('dias_corridos', models.DateField()),
                ('dias_uteis_banco', models.DateField()),
                ('dias_uteis_tribunal', models.DateField()),
                ('tribunal', models.CharField(blank=True, max_length=254, null=True)),
                ('adv_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provimento', models.CharField(choices=[('F', 'Feriado'), ('P', 'Provimento'), ('I', 'Indisponibilidade')], default='F', max_length=1)),
            ],
        ),
    ]
