# Generated by Django 4.0.5 on 2022-08-02 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcprazo', '0002_alter_calculaprazo_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='data_feriado',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feriado',
            name='feriado',
            field=models.CharField(default=datetime.date(1900, 1, 1), max_length=254),
            preserve_default=False,
        ),
    ]
